name: Test Checks

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests-release:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 12000

      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install python and pip
        run: sudo apt install -y python3 && sudo apt install -y python3-pip

      - name: setup env
        run: chmod +x ./scripts/setup_in_ubuntu.sh && ./scripts/setup_in_ubuntu.sh

      # - name: add artifactory
      #   run: conan remote add artifactory https://conan.buzeta.net/artifactory/api/conan/conan-local

      - name: install dependencies conan
        run: chmod +x ./scripts/install_dependencies.sh && ./scripts/install_dependencies.sh

      - name: base build
        run: chmod +x ./scripts/build.sh && ./scripts/build.sh -b Release

      - name: build with grammar
        run: chmod +x ./scripts/build_grammar.sh && ./scripts/build_grammar.sh -b Release

      - name: benchmark stock query
        run: chmod +x ./scripts/build_and_benchmark_stock_queries.sh && ./scripts/build_and_benchmark_stock_queries.sh -b Release

      - name: benchmark smart home query
        run: chmod +x ./scripts/build_and_benchmark_smart_homes_queries.sh && ./scripts/build_and_benchmark_smart_homes_queries.sh -b Release

      - name: benchmark taxi query
        run: chmod +x ./scripts/build_and_benchmark_taxi_queries.sh && ./scripts/build_and_benchmark_taxi_queries.sh -b Release

      - uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: |
            src/targets/experiments/*/benchmark.csv
